### ISSUE TITLE
Support for PCK Processor CRL mode

### ISSUE THREAD

**Issue by ThorodanBrom** [Cosmian/intel-sgx-ra#3]
Hello,

This library is really great, thanks for open-sourcing it! Would you consider officially supporting PCK-processor mode in the remote attestation? As of now, `platform` is hardcoded here:
https://github.com/Cosmian/intel-sgx-ra/blob/423f9a35f93732d0bbe8f15cefe45279e86497bc/src/intel_sgx_ra/attest.py#L47

The function can take both `platform` and `processor` - so can it be an argument passed when calling the CLI command?

I'm happy to help with a PR.

Thanks

**Comment by grydz** [comment]
Hi @ThorodanBrom,

Thank you for pointing this! We can had the support of _Intel SGX PCK Processor CA_ in the next release.

I'm wondering if it's enought to check the CN in the subject and choose accordingly: https://github.com/Cosmian/intel-sgx-ra/pull/2/commits/a5dbf041baa9550aa89cad5c5080ebd09ab709ba.

What do you think?

**Comment by ThorodanBrom** [comment]
Hello @grydz,

The CN approach is a good idea, the PCK certificate spec ([here](https://api.trustedservices.intel.com/documents/Intel_SGX_PCK_Certificate_CRL_Spec-1.4.pdf), section 1.3.5) specifies that the CN can be only those 2 values.

Thanks for adding it and thanks again for open sourcing this library!
